version: '3.9'

name: schocken

networks:
  schocken:
    name: schocken

volumes:
  schocken-pgdata:
    name: schocken-pgdata

services:
  postgres:
    image: postgres:15.7
    restart: always
    container_name: schocken-postgres
    networks:
      - schocken
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootPW
      HOPTIMISTEN_DATABASE_NAME: hoptimisten
    ports:
      - 5439:5432
    volumes:
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
      - schocken-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  schocken-backend:
    image: schocken-backend:latest
    build:
      context: ../
    restart: always
    container_name: schocken-backend
    networks:
      - schocken
    ports:
      - 3000:3000
